{
  "name": "Personal Fitness BI",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "de-CH",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "de-CH",
    "tables": [
      {
        "name": "fact_Training",
        "lineageTag": "a3959c32-04ee-4f09-bb01-276d27ba2535",
        "columns": [
          {
            "name": "Dauer (in Minuten)",
            "dataType": "int64",
            "sourceColumn": "Dauer (in Minuten)",
            "formatString": "0",
            "lineageTag": "023100b9-fb34-497d-b69c-f76e717feb87",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Distanz (in km)",
            "dataType": "double",
            "sourceColumn": "Distanz (in km)",
            "formatString": "0",
            "lineageTag": "d5698842-cc62-45d4-9bee-6bc30f257185",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Durchschnitts-Puls",
            "dataType": "int64",
            "sourceColumn": "Durchschnitts-Puls",
            "formatString": "0",
            "lineageTag": "23298126-0112-40ef-8aa6-0b3b9a8ac757",
            "summarizeBy": "average",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "Beschreibung / Notizen",
            "dataType": "string",
            "sourceColumn": "Beschreibung / Notizen",
            "lineageTag": "8cbd5237-e4fd-425a-90e3-bc9392d81f16",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id",
            "formatString": "0",
            "lineageTag": "199bf98a-5c08-4779-80c7-21267745c148",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "TrainingArt_Key",
            "dataType": "int64",
            "sourceColumn": "TrainingArt_Key",
            "formatString": "0",
            "lineageTag": "fc04fdd3-6b9e-4fc6-b934-93b10b4e1752",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Datum Nr",
            "dataType": "int64",
            "sourceColumn": "Datum Nr",
            "formatString": "0",
            "lineageTag": "0d0b338d-8459-4b1b-92c7-5ba9866a188c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fact_Training",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // 1. Zugriff auf die aufbereitete Staging-Tabelle (Ihre bereinigte Quelle)",
                "    Quelle = source_Training,",
                "",
                "    // 2. Lookup der Trainingsart-ID: ",
                "    // Wir verknüpfen die Fakten mit der Dimension \"dim_Trainingsarten\", um den numerischen Schlüssel zu erhalten.",
                "    #\"Zusammengeführte Abfragen\" = Table.NestedJoin(Quelle, {\"Trainingsart\"}, dim_Trainingsarten, {\"Trainingsart\"}, \"dim_Trainingsarten\", JoinKind.LeftOuter),",
                "",
                "    // 3. Extraktion des Schlüssels: ",
                "    // Nur die Spalte \"TrainingArt_Key\" wird aus der Dimensionstabelle übernommen.",
                "    #\"Erweiterte dim_Trainingsarten\" = Table.ExpandTableColumn(#\"Zusammengeführte Abfragen\", \"dim_Trainingsarten\", {\"TrainingArt_Key\"}, {\"TrainingArt_Key\"}),",
                "",
                "    // 4. Bereinigung der Faktentabelle: ",
                "    // Wir entfernen Metadaten (E-Mail, Name) und die ursprünglichen Textfelder.",
                "    // Das Feld \"Datum\" wird hier entfernt, da wir bereits die \"Datum Nr\" (DateKey) für die Relation zur Zeit-Dimension haben.",
                "    #\"Entfernte Spalten\" = Table.RemoveColumns(#\"Erweiterte dim_Trainingsarten\",{\"Startzeit\", \"Fertigstellungszeit\", \"E-Mail\", \"Name\", \"Trainingsart\", \"Datum\"})",
                "in",
                "    #\"Entfernte Spalten\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "dim_Kalender",
        "lineageTag": "f0f51e87-8a7c-4716-93eb-cb7a77293687",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Jahr",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Jahr]",
            "formatString": "0",
            "lineageTag": "b1bddb9c-978e-4e38-b78c-a00642e96821",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Monat",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Monat]",
            "lineageTag": "f4f3a4f3-0c81-4fd0-a17f-a721e7c0d42e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Kalenderwoche",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Kalenderwoche]",
            "formatString": "0",
            "lineageTag": "368e8135-2348-4bca-8828-3f05b7708cdc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "JahrWoche",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[JahrWoche]",
            "lineageTag": "66b2e775-4b37-41a5-9d8d-d2ef68c6fe8d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Wochentag",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Wochentag]",
            "lineageTag": "d7bee4cf-d733-4ac3-a150-b73fac63b93d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Datum Nr",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Datum Nr]",
            "formatString": "0",
            "lineageTag": "fa808b6a-a106-48e2-b838-8024d9b68005",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Datum",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Datum]",
            "formatString": "Short Date",
            "lineageTag": "18e2dc65-0f05-4d85-b17d-a8b374111236",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dim_Kalender",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR StartDatum = DATE(2025, 1, 1)",
                "VAR EndDatum = DATE(2026, 12, 31)",
                "-- Erzeugt die Basistabelle mit der Standardspalte [Date]",
                "VAR BasisKalender = CALENDAR(StartDatum, EndDatum)",
                "",
                "RETURN",
                "SELECTCOLUMNS (",
                "    ADDCOLUMNS (",
                "        BasisKalender,",
                "        \"Datum Nr\", YEAR([Date]) * 10000 + MONTH([Date]) * 100 + DAY([Date]),",
                "        \"Jahr\", YEAR([Date]),",
                "        \"Monat\", FORMAT([Date], \"mmmm\"),",
                "        \"Kalenderwoche\", WEEKNUM([Date], 2),",
                "        \"JahrWoche\", FORMAT([Date], \"yyyy\") & \"-\" & FORMAT(WEEKNUM([Date], 21), \"00\"),",
                "        \"Wochentag\", FORMAT([Date], \"dddd\")",
                "    ),",
                "    -- Hier definieren wir die Namen der Spalten für die fertige Tabelle",
                "    \"Datum\", [Date], ",
                "    \"Datum Nr\", [Datum Nr],",
                "    \"Jahr\", [Jahr],",
                "    \"Monat\", [Monat],",
                "    \"Kalenderwoche\", [Kalenderwoche],",
                "    \"JahrWoche\", [JahrWoche],",
                "    \"Wochentag\", [Wochentag]",
                ")"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e5b2a917d06c4a7d8d6dccaea11a4e57"
          }
        ]
      },
      {
        "name": "_Kennzahlen",
        "lineageTag": "7dfcb300-f648-495e-808f-ccca5fc8e592",
        "partitions": [
          {
            "name": "_Kennzahlen",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // 1. Erzeugt eine leere Tabelle aus einem Base64-String (Das ist der Standard-Code für \"Daten eingeben\")",
                "    // \"i44FAA==\" ist der kodierte Wert für eine leere Zelle/Tabelle.",
                "    Quelle = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Spalte \"\"1\"\"\" = _t]),",
                "    ",
                "    // 2. Setzt den Datentyp der (leeren) Spalte auf Text, damit Power BI damit arbeiten kann",
                "    #\"Geänderter Typ\" = Table.TransformColumnTypes(Quelle,{{\"Spalte \"\"1\"\"\", type text}}),",
                "",
                "    // 3. Spalte entfernen",
                "    // Wir löschen die automatisch erstellte Hilfsspalte \"Spalte 1\".",
                "    // Zurück bleibt eine Tabelle ohne Spalten – die perfekte \"Hülle\" für Measures.",
                "    #\"Entfernte Spalten\" = Table.RemoveColumns(#\"Geänderter Typ\",{\"Spalte \"\"1\"\"\"})",
                "in",
                "    // 4. Gibt die leere Tabelle zurück, die wir als Container für Measures nutzen",
                "    // Nach dem Laden in Power BI können Sie hier alle Kennzahlen (z.B. Summe Dauer) ablegen.",
                "    #\"Entfernte Spalten\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Dauer (Std)",
            "expression": "SUM('fact_Training'[Dauer (in Minuten)]) / 60",
            "formatString": "0.00",
            "lineageTag": "0167ca47-c270-4de7-a9ad-374f95087b3c"
          },
          {
            "name": "Ø kmh",
            "expression": "DIVIDE( SUM('fact_Training'[Distanz (in km)]), [Dauer (Std)], 0 )",
            "formatString": "#,0.0",
            "lineageTag": "613c6e80-742b-4204-8a82-0ae3beff06ab"
          },
          {
            "name": "Effizienz",
            "expression": "DIVIDE( [Ø kmh], AVERAGE('fact_Training'[Durchschnitts-Puls]), 0 )",
            "formatString": "0.00",
            "lineageTag": "b342d0a2-2064-49ad-8c58-1a40a3a98b79"
          },
          {
            "name": "Distanz (km)",
            "expression": "SUM('fact_Training'[Distanz (in km)])",
            "formatString": "0.0",
            "lineageTag": "6b620efd-2365-4f1b-ac36-792a3df00372"
          },
          {
            "name": "Trainingseinheiten",
            "expression": "DISTINCTCOUNT( fact_Training[ID] )",
            "formatString": "0",
            "lineageTag": "54d32705-f951-40c2-98bf-cedfc3289dd1"
          },
          {
            "name": "Ø Puls",
            "expression": "DIVIDE( SUM('fact_Training'[Durchschnitts-Puls]), [Trainingseinheiten], 0 )",
            "formatString": "0",
            "lineageTag": "d068b0b0-0b91-4090-995e-a419d9dfb633"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dim_Trainingsarten",
        "lineageTag": "cb73cec5-c595-47ba-834a-01d28ab402be",
        "columns": [
          {
            "name": "Trainingsart",
            "dataType": "string",
            "sourceColumn": "Trainingsart",
            "lineageTag": "5b0dee17-6b1b-4bbb-8248-01d167ad64ad",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TrainingArt_Key",
            "dataType": "int64",
            "sourceColumn": "TrainingArt_Key",
            "formatString": "0",
            "lineageTag": "780d5614-5bc0-42ea-bd43-fee3c309857f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dim_Trainingsarten",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // 1. Bezug auf die Faktentabelle nehmen",
                "    // Wir laden die bereits existierende Tabelle \"source_Training\" als Quelle.",
                "    Quelle = source_Training,",
                "",
                "    // 2. Spaltenauswahl",
                "    // Wir behalten nur die Spalte \"Trainingsart\" und entfernen alle anderen (Datum, Dauer etc.).",
                "    // Diese Spalte basiert auf dem Feld \"Was hast du gemacht?\" aus Ihren Quelldaten.",
                "    #\"Andere entfernte Spalten\" = Table.SelectColumns(Quelle,{\"Trainingsart\"}),",
                "    ",
                "    // 3. Duplikate entfernen",
                "    // Wir wollen jede Sportart (wie z.B. \"Schwimmen\", \"Radfahren\", \"Laufen\" oder \"Krafttraining\") nur genau einmal in der Liste haben.",
                "    // Das Ergebnis ist eine eindeutige Liste aller Sportarten, die als Filter im Sternschema dient.",
                "    #\"Entfernte Duplikate\" = Table.Distinct(#\"Andere entfernte Spalten\"),",
                "",
                "    // 4. Indexspalte als Schlüssel (Surrogate Key) hinzufügen",
                "    // Wir erstellen einen numerischen Primärschlüssel (Ganzzahl), der für die Verknüpfung im Modell genutzt wird.",
                "    // Dieser Schlüssel (z. B. 1 für Schwimmen, 2 für Radfahren) optimiert die Performance gegenüber Text-Verknüpfungen.",
                "    #\"Hinzugefügter Index\" = Table.AddIndexColumn(#\"Entfernte Duplikate\", \"TrainingArt_Key\", 1, 1, Int64.Type)",
                "",
                "in",
                "    // Rückgabe der fertigen Dimensionstabelle \"dim_Trainingsarten\"",
                "    #\"Hinzugefügter Index\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "source_Training",
        "isHidden": true,
        "lineageTag": "8621b4b3-dd84-41f0-b9a8-42632d93913a",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id",
            "formatString": "0",
            "lineageTag": "c77da1b6-3cb9-458f-881d-c1fc0799afe6",
            "summarizeBy": "count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Startzeit",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Startzeit",
            "formatString": "General Date",
            "lineageTag": "3adac929-75ad-4992-800d-5eebf4049209",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Fertigstellungszeit",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Fertigstellungszeit",
            "formatString": "General Date",
            "lineageTag": "7ab7eb31-c95a-466d-9a47-740df66636b1",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "E-Mail",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "E-Mail",
            "lineageTag": "4e3d6411-9846-4e8d-90fb-91aa5497c2fb",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "lineageTag": "d3401e2e-9937-43ab-b54a-b20299d6acc2",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Datum",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Datum",
            "formatString": "General Date",
            "lineageTag": "44df8e05-a863-4d9e-802e-5124c21e6411",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Trainingsart",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Trainingsart",
            "lineageTag": "a9b40c28-2f9b-4ea0-8df7-63d6443a7d57",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Dauer (in Minuten)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Dauer (in Minuten)",
            "formatString": "0",
            "lineageTag": "8b43bf83-760c-4468-ba24-86cbf948c3d8",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Distanz (in km)",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Distanz (in km)",
            "lineageTag": "897efc11-011f-4838-92c2-5b94ce24f977",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Durchschnitts-Puls",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Durchschnitts-Puls",
            "formatString": "0",
            "lineageTag": "73e5d015-5be4-4e25-86a1-d64bf2e0cddc",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Beschreibung / Notizen",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Beschreibung / Notizen",
            "lineageTag": "b21aa941-f3cc-437a-9c04-99c5dedbce8e",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Datum Nr",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Datum Nr",
            "formatString": "0",
            "lineageTag": "f8ad71fb-be66-4eb3-b36d-1e48d573b195",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "source_Training",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // 1. Zugriff auf die lokale Datei (Pfad ist benutzerspezifisch!)",
                "    Quelle = Excel.Workbook(File.Contents(\"C:\\Users\\andre\\OneDrive\\Trainingseintrag.xlsx\"), null, true),",
                "",
                "    // 2. Navigation zur strukturierten Tabelle aus Forms",
                "    Tabelle1_Table = Quelle{[Item=\"OfficeForms.Table\",Kind=\"Table\"]}[Data],",
                "",
                "    // 3. Bereinigung der Dezimaltrennzeichen: Komma durch Punkt ersetzen, ",
                "    // um die Spalte \"Distanz (in km)\" korrekt in eine Zahl umwandeln zu können",
                "    #\"Ersetzter Wert\" = Table.ReplaceValue(Tabelle1_Table,\",\",\".\",Replacer.ReplaceText,{\"Distanz (in km)\"}),",
                "",
                "    // 4. Spalten umbenennen: \"Was hast du gemacht?\" wird zu \"Trainingsart\" und ",
                "    // \"Wann war das Training?\" zu \"Datum\", um das Modell lesbarer zu machen",
                "    #\"Umbenannte Spalten\" = Table.RenameColumns(#\"Ersetzter Wert\",{{\"Was hast du gemacht?\", \"Trainingsart\"}, {\"Wann war das Training?\", \"Datum\"}}),",
                "",
                "    // 5. Erstellung des Integers-Schlüssels (DateKey): ",
                "    // Berechnung eines YYYYMMDD Wertes aus dem Datum für die performante Relation zur Kalendertabelle",
                "    #\"Hinzugefügte benutzerdefinierte Spalte\" = Table.AddColumn(#\"Umbenannte Spalten\", \"Datum Nr\", each Date.Year([Datum]) * 10000 + ",
                "    Date.Month([Datum]) * 100 + ",
                "    Date.Day([Datum])),",
                "",
                "    // 6. Typkonvertierung: Festlegung der Datentypen für alle Spalten, ",
                "    // insbesondere Ganzzahlen für ID/Dauer/Puls und Dezimalzahlen für die Distanz",
                "    #\"Geänderter Typ\" = Table.TransformColumnTypes(#\"Hinzugefügte benutzerdefinierte Spalte\",{",
                "        {\"Startzeit\", type datetime}, ",
                "        {\"Fertigstellungszeit\", type datetime}, ",
                "        {\"Datum\", type datetime}, ",
                "        {\"Id\", Int64.Type}, ",
                "        {\"E-Mail\", type text}, ",
                "        {\"Name\", type text}, ",
                "        {\"Trainingsart\", type text}, ",
                "        {\"Dauer (in Minuten)\", Int64.Type}, ",
                "        {\"Distanz (in km)\", type number}, ",
                "        {\"Durchschnitts-Puls\", Int64.Type}, ",
                "        {\"Beschreibung / Notizen\", type text}, ",
                "        {\"Datum Nr\", Int64.Type}",
                "    })",
                "in",
                "    #\"Geänderter Typ\""
              ]
            }
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "11aa3ab2-69ff-4dac-6780-5c0ded0f9bb9",
        "fromTable": "fact_Training",
        "fromColumn": "TrainingArt_Key",
        "toTable": "dim_Trainingsarten",
        "toColumn": "TrainingArt_Key"
      },
      {
        "name": "a99c32cb-a3e7-e8c0-37b0-127ef824a9ca",
        "fromTable": "fact_Training",
        "fromColumn": "Datum Nr",
        "toTable": "dim_Kalender",
        "toColumn": "Datum Nr"
      }
    ],
    "cultures": [
      {
        "name": "de-CH",
        "linguisticMetadata": {
          "content": {
            "Version": "1.0.0",
            "Language": "en-US"
          },
          "contentType": "json"
        }
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"_Kennzahlen\",\"source_Training\",\"fact_Training\",\"dim_Trainingsarten\"]"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Perspectives\",\"Relationships\",\"Roles\",\"Shared Expressions\",\"Tables\",\"Tables/Calculation Items\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Translations\"]}"
      }
    ]
  }
}